<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Ruoyu.Study.Vocabulary.Domain.csproj" />
    <ProjectReference Include="..\Database\Ruoyu.Study.Vocabulary.Database.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Ruoyu.Study.Vocabulary.Service.Tests" />
  </ItemGroup>
</Project>
