version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Singapore
    groups:
      frontend-dependencies:
        patterns: ["*"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /src
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: Asia/Singapore
    groups:
      dotnet-dependencies:
        patterns: ["*"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /src/Host
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Singapore
    ignore:
      - dependency-name: node
        update-types: ["version-update:semver-major"]
      - dependency-name: dotnet/sdk
        update-types: ["version-update:semver-major"]
      - dependency-name: dotnet/aspnet
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:45"
      timezone: Asia/Singapore
    groups:
      github-actions:
        patterns: ["*"]
    open-pull-requests-limit: 5
