// <auto-generated />
using System;
using Lexarbor.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lexarbor.Database.Migrations
{
    [DbContext(typeof(VocabularyDbContext))]
    [Migration("20260821023350_AddNormalizedWordColumn")]
    partial class AddNormalizedWordColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyBookEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("book_name");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_order");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("TEXT")
                        .HasColumnName("education_level");

                    b.Property<string>("Grade")
                        .HasColumnType("TEXT")
                        .HasColumnName("grade");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_url");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT")
                        .HasColumnName("publisher");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("vocabulary_book");
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedWord")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_word")
                        .HasComputedColumnSql("lower(trim(word))", false);

                    b.Property<string>("PhoneticUk")
                        .HasColumnType("TEXT")
                        .HasColumnName("phonetic_uk");

                    b.Property<string>("PhoneticUs")
                        .HasColumnType("TEXT")
                        .HasColumnName("phonetic_us");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedWord");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("vocabulary");
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyMeaningEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("book_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Example")
                        .HasColumnType("TEXT")
                        .HasColumnName("example");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("meaning");

                    b.Property<string>("NormalizedMeaning")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_meaning")
                        .HasComputedColumnSql("trim(meaning)", true);

                    b.Property<string>("NormalizedPartOfSpeech")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_part_of_speech")
                        .HasComputedColumnSql("lower(trim(coalesce(part_of_speech, '')))", true);

                    b.Property<string>("PartOfSpeech")
                        .HasColumnType("TEXT")
                        .HasColumnName("part_of_speech");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VocabularyId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vocabulary_id");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId");

                    b.HasIndex("BookId", "VocabularyId");

                    b.HasIndex("VocabularyId", "BookId", "NormalizedPartOfSpeech", "NormalizedMeaning")
                        .IsUnique();

                    b.ToTable("vocabulary_meaning");
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyMeaningEntity", b =>
                {
                    b.HasOne("Lexarbor.Database.Entities.VocabularyBookEntity", "Book")
                        .WithMany("Meanings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lexarbor.Database.Entities.VocabularyEntity", "Vocabulary")
                        .WithMany()
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyBookEntity", b =>
                {
                    b.Navigation("Meanings");
                });
#pragma warning restore 612, 618
        }
    }
}
