// <auto-generated />
using System;
using Lexarbor.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lexarbor.Database.Migrations
{
    [DbContext(typeof(VocabularyDbContext))]
    [Migration("20261001125645_AddServiceAuditLogs")]
    partial class AddServiceAuditLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Lexarbor.Database.Entities.AdminSessionEntity", b =>
                {
                    b.Property<string>("HandleHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("handle_hash");

                    b.Property<long>("ExpiresAtUnixMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at_unix_ms");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protected_payload");

                    b.HasKey("HandleHash");

                    b.HasIndex("ExpiresAtUnixMs", "HandleHash");

                    b.ToTable("admin_session");
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyBookEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("book_name");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_order");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("TEXT")
                        .HasColumnName("education_level");

                    b.Property<string>("Grade")
                        .HasColumnType("TEXT")
                        .HasColumnName("grade");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_url");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT")
                        .HasColumnName("publisher");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("vocabulary_book");
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyBookUnitEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("book_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "Number")
                        .IsUnique();

                    b.HasIndex("Id", "BookId")
                        .IsUnique();

                    b.ToTable("vocabulary_book_unit");
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedWord")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_word")
                        .HasComputedColumnSql("lower(trim(word))", false);

                    b.Property<string>("PhoneticUk")
                        .HasColumnType("TEXT")
                        .HasColumnName("phonetic_uk");

                    b.Property<string>("PhoneticUs")
                        .HasColumnType("TEXT")
                        .HasColumnName("phonetic_us");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedWord");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("vocabulary");
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyMeaningEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("book_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Example")
                        .HasColumnType("TEXT")
                        .HasColumnName("example");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("meaning");

                    b.Property<string>("NormalizedMeaning")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_meaning")
                        .HasComputedColumnSql("trim(meaning)", true);

                    b.Property<string>("NormalizedPartOfSpeech")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_part_of_speech")
                        .HasComputedColumnSql("lower(trim(coalesce(part_of_speech, '')))", true);

                    b.Property<string>("PartOfSpeech")
                        .HasColumnType("TEXT")
                        .HasColumnName("part_of_speech");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VocabularyId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vocabulary_id");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId");

                    b.HasIndex("BookId", "VocabularyId");

                    b.HasIndex("Id", "BookId")
                        .IsUnique();

                    b.HasIndex("VocabularyId", "BookId", "NormalizedPartOfSpeech", "NormalizedMeaning")
                        .IsUnique();

                    b.ToTable("vocabulary_meaning");
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyMeaningUnitEntity", b =>
                {
                    b.Property<string>("UnitId")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_id");

                    b.Property<string>("MeaningId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meaning_id");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("section");

                    b.Property<string>("EntryKind")
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("entry_kind");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("book_id");

                    b.HasKey("UnitId", "MeaningId", "Section", "EntryKind");

                    b.HasIndex("MeaningId", "BookId");

                    b.HasIndex("UnitId", "BookId");

                    b.ToTable("vocabulary_meaning_unit", t =>
                        {
                            t.HasCheckConstraint("CK_vocabulary_meaning_unit_entry_kind", "entry_kind IN ('', 'word', 'phrase')");

                            t.HasCheckConstraint("CK_vocabulary_meaning_unit_section", "section IN ('', 'A', 'B')");
                        });
                });

            modelBuilder.Entity("ServiceMantle.Persistence.Relational.DataProtection.DataProtectionKeyEntity", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("service_id");

                    b.Property<string>("KeyId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_id");

                    b.Property<string>("EncryptedXml")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("encrypted_xml");

                    b.HasKey("ServiceId", "KeyId");

                    b.ToTable("service_data_protection_keys", (string)null);
                });

            modelBuilder.Entity("ServiceMantle.Persistence.Relational.Mapping.ManagementAuditLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_ip");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("OperatorDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_display_name");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_source");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER")
                        .HasColumnName("outcome");

                    b.Property<string>("SecurityDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_description");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_occurred_at_utc_id");

                    b.HasIndex("Action", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_action_occurred_at_utc_id");

                    b.HasIndex("OperatorId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_operator_id_occurred_at_utc_id");

                    b.HasIndex("TargetId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_target_id_occurred_at_utc_id");

                    b.HasIndex("TargetType", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_target_type_occurred_at_utc_id");

                    b.HasIndex("TargetType", "TargetId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_target_occurred_at_utc_id");

                    b.ToTable("service_audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_audit_logs_action_length", "action IS NULL OR octet_length(action) <= 800");

                            t.HasCheckConstraint("ck_service_audit_logs_client_ip_length", "client_ip IS NULL OR octet_length(client_ip) <= 256");

                            t.HasCheckConstraint("ck_service_audit_logs_correlation_id_length", "correlation_id IS NULL OR octet_length(correlation_id) <= 512");

                            t.HasCheckConstraint("ck_service_audit_logs_id_length", "id IS NULL OR octet_length(id) <= 144");

                            t.HasCheckConstraint("ck_service_audit_logs_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_service_audit_logs_metadata_json_length", "metadata_json IS NULL OR octet_length(metadata_json) <= 262144");

                            t.HasCheckConstraint("ck_service_audit_logs_operator_display_name_length", "operator_display_name IS NULL OR octet_length(operator_display_name) <= 1024");

                            t.HasCheckConstraint("ck_service_audit_logs_operator_id_length", "operator_id IS NULL OR octet_length(operator_id) <= 1024");

                            t.HasCheckConstraint("ck_service_audit_logs_operator_source_length", "operator_source IS NULL OR octet_length(operator_source) <= 400");

                            t.HasCheckConstraint("ck_service_audit_logs_security_description_length", "security_description IS NULL OR octet_length(security_description) <= 16000");

                            t.HasCheckConstraint("ck_service_audit_logs_target_id_length", "target_id IS NULL OR octet_length(target_id) <= 1024");

                            t.HasCheckConstraint("ck_service_audit_logs_target_type_length", "target_type IS NULL OR octet_length(target_type) <= 800");
                        });
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyBookUnitEntity", b =>
                {
                    b.HasOne("Lexarbor.Database.Entities.VocabularyBookEntity", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyMeaningEntity", b =>
                {
                    b.HasOne("Lexarbor.Database.Entities.VocabularyBookEntity", "Book")
                        .WithMany("Meanings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lexarbor.Database.Entities.VocabularyEntity", "Vocabulary")
                        .WithMany()
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyMeaningUnitEntity", b =>
                {
                    b.HasOne("Lexarbor.Database.Entities.VocabularyMeaningEntity", "Meaning")
                        .WithMany()
                        .HasForeignKey("MeaningId", "BookId")
                        .HasPrincipalKey("Id", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lexarbor.Database.Entities.VocabularyBookUnitEntity", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId", "BookId")
                        .HasPrincipalKey("Id", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meaning");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Lexarbor.Database.Entities.VocabularyBookEntity", b =>
                {
                    b.Navigation("Meanings");
                });
#pragma warning restore 612, 618
        }
    }
}
